package com.diffwind.dao.model;

public class EastmoneyStockRzrqJson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eastmoney_stock_rzrq_json.rzrq_data
     *
     * @mbggenerated
     */
    private Object rzrqData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eastmoney_stock_rzrq_json.rzrq_data
     *
     * @return the value of eastmoney_stock_rzrq_json.rzrq_data
     *
     * @mbggenerated
     */
    public Object getRzrqData() {
        return rzrqData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eastmoney_stock_rzrq_json.rzrq_data
     *
     * @param rzrqData the value for eastmoney_stock_rzrq_json.rzrq_data
     *
     * @mbggenerated
     */
    public void setRzrqData(Object rzrqData) {
        this.rzrqData = rzrqData;
    }
}