package com.diffwind.dao.model;

public class SinaZjhhangyeStock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sina_zjhhangye_stock.hycode
     *
     * @mbggenerated
     */
    private String hycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sina_zjhhangye_stock.hyname
     *
     * @mbggenerated
     */
    private String hyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sina_zjhhangye_stock.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sina_zjhhangye_stock.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sina_zjhhangye_stock.hycode
     *
     * @return the value of sina_zjhhangye_stock.hycode
     *
     * @mbggenerated
     */
    public String getHycode() {
        return hycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sina_zjhhangye_stock.hycode
     *
     * @param hycode the value for sina_zjhhangye_stock.hycode
     *
     * @mbggenerated
     */
    public void setHycode(String hycode) {
        this.hycode = hycode == null ? null : hycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sina_zjhhangye_stock.hyname
     *
     * @return the value of sina_zjhhangye_stock.hyname
     *
     * @mbggenerated
     */
    public String getHyname() {
        return hyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sina_zjhhangye_stock.hyname
     *
     * @param hyname the value for sina_zjhhangye_stock.hyname
     *
     * @mbggenerated
     */
    public void setHyname(String hyname) {
        this.hyname = hyname == null ? null : hyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sina_zjhhangye_stock.symbol
     *
     * @return the value of sina_zjhhangye_stock.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sina_zjhhangye_stock.symbol
     *
     * @param symbol the value for sina_zjhhangye_stock.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sina_zjhhangye_stock.name
     *
     * @return the value of sina_zjhhangye_stock.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sina_zjhhangye_stock.name
     *
     * @param name the value for sina_zjhhangye_stock.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}