package com.diffwind.dao.model;

public class SinaZjhhangye {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sina_zjhhangye.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sina_zjhhangye.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sina_zjhhangye.code
     *
     * @return the value of sina_zjhhangye.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sina_zjhhangye.code
     *
     * @param code the value for sina_zjhhangye.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sina_zjhhangye.name
     *
     * @return the value of sina_zjhhangye.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sina_zjhhangye.name
     *
     * @param name the value for sina_zjhhangye.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}