package com.diffwind.dao.model;

import java.util.Date;

public class TdxStockDay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_stock_day.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_stock_day.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_stock_day.open
     *
     * @mbggenerated
     */
    private Double open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_stock_day.high
     *
     * @mbggenerated
     */
    private Double high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_stock_day.low
     *
     * @mbggenerated
     */
    private Double low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_stock_day.close
     *
     * @mbggenerated
     */
    private Double close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_stock_day.amt
     *
     * @mbggenerated
     */
    private Double amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdx_stock_day.vol
     *
     * @mbggenerated
     */
    private Double vol;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_stock_day.symbol
     *
     * @return the value of tdx_stock_day.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_stock_day.symbol
     *
     * @param symbol the value for tdx_stock_day.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_stock_day.date
     *
     * @return the value of tdx_stock_day.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_stock_day.date
     *
     * @param date the value for tdx_stock_day.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_stock_day.open
     *
     * @return the value of tdx_stock_day.open
     *
     * @mbggenerated
     */
    public Double getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_stock_day.open
     *
     * @param open the value for tdx_stock_day.open
     *
     * @mbggenerated
     */
    public void setOpen(Double open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_stock_day.high
     *
     * @return the value of tdx_stock_day.high
     *
     * @mbggenerated
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_stock_day.high
     *
     * @param high the value for tdx_stock_day.high
     *
     * @mbggenerated
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_stock_day.low
     *
     * @return the value of tdx_stock_day.low
     *
     * @mbggenerated
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_stock_day.low
     *
     * @param low the value for tdx_stock_day.low
     *
     * @mbggenerated
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_stock_day.close
     *
     * @return the value of tdx_stock_day.close
     *
     * @mbggenerated
     */
    public Double getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_stock_day.close
     *
     * @param close the value for tdx_stock_day.close
     *
     * @mbggenerated
     */
    public void setClose(Double close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_stock_day.amt
     *
     * @return the value of tdx_stock_day.amt
     *
     * @mbggenerated
     */
    public Double getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_stock_day.amt
     *
     * @param amt the value for tdx_stock_day.amt
     *
     * @mbggenerated
     */
    public void setAmt(Double amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdx_stock_day.vol
     *
     * @return the value of tdx_stock_day.vol
     *
     * @mbggenerated
     */
    public Double getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdx_stock_day.vol
     *
     * @param vol the value for tdx_stock_day.vol
     *
     * @mbggenerated
     */
    public void setVol(Double vol) {
        this.vol = vol;
    }
}