package com.diffwind.dao.model;

import java.util.Date;

public class XueqiuStockShareschg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_shareschg.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_shareschg.publishdate
     *
     * @mbggenerated
     */
    private Date publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_shareschg.begindate
     *
     * @mbggenerated
     */
    private Date begindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_shareschg.totalshare
     *
     * @mbggenerated
     */
    private Double totalshare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_shareschg.totalsharechg
     *
     * @mbggenerated
     */
    private Double totalsharechg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_shareschg.skchgexp
     *
     * @mbggenerated
     */
    private String skchgexp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_shareschg.fcircskamt
     *
     * @mbggenerated
     */
    private Double fcircskamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_shareschg.circskamt
     *
     * @mbggenerated
     */
    private Double circskamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_shareschg.ncircamt
     *
     * @mbggenerated
     */
    private Double ncircamt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_shareschg.symbol
     *
     * @return the value of xueqiu_stock_shareschg.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_shareschg.symbol
     *
     * @param symbol the value for xueqiu_stock_shareschg.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_shareschg.publishdate
     *
     * @return the value of xueqiu_stock_shareschg.publishdate
     *
     * @mbggenerated
     */
    public Date getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_shareschg.publishdate
     *
     * @param publishdate the value for xueqiu_stock_shareschg.publishdate
     *
     * @mbggenerated
     */
    public void setPublishdate(Date publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_shareschg.begindate
     *
     * @return the value of xueqiu_stock_shareschg.begindate
     *
     * @mbggenerated
     */
    public Date getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_shareschg.begindate
     *
     * @param begindate the value for xueqiu_stock_shareschg.begindate
     *
     * @mbggenerated
     */
    public void setBegindate(Date begindate) {
        this.begindate = begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_shareschg.totalshare
     *
     * @return the value of xueqiu_stock_shareschg.totalshare
     *
     * @mbggenerated
     */
    public Double getTotalshare() {
        return totalshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_shareschg.totalshare
     *
     * @param totalshare the value for xueqiu_stock_shareschg.totalshare
     *
     * @mbggenerated
     */
    public void setTotalshare(Double totalshare) {
        this.totalshare = totalshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_shareschg.totalsharechg
     *
     * @return the value of xueqiu_stock_shareschg.totalsharechg
     *
     * @mbggenerated
     */
    public Double getTotalsharechg() {
        return totalsharechg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_shareschg.totalsharechg
     *
     * @param totalsharechg the value for xueqiu_stock_shareschg.totalsharechg
     *
     * @mbggenerated
     */
    public void setTotalsharechg(Double totalsharechg) {
        this.totalsharechg = totalsharechg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_shareschg.skchgexp
     *
     * @return the value of xueqiu_stock_shareschg.skchgexp
     *
     * @mbggenerated
     */
    public String getSkchgexp() {
        return skchgexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_shareschg.skchgexp
     *
     * @param skchgexp the value for xueqiu_stock_shareschg.skchgexp
     *
     * @mbggenerated
     */
    public void setSkchgexp(String skchgexp) {
        this.skchgexp = skchgexp == null ? null : skchgexp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_shareschg.fcircskamt
     *
     * @return the value of xueqiu_stock_shareschg.fcircskamt
     *
     * @mbggenerated
     */
    public Double getFcircskamt() {
        return fcircskamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_shareschg.fcircskamt
     *
     * @param fcircskamt the value for xueqiu_stock_shareschg.fcircskamt
     *
     * @mbggenerated
     */
    public void setFcircskamt(Double fcircskamt) {
        this.fcircskamt = fcircskamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_shareschg.circskamt
     *
     * @return the value of xueqiu_stock_shareschg.circskamt
     *
     * @mbggenerated
     */
    public Double getCircskamt() {
        return circskamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_shareschg.circskamt
     *
     * @param circskamt the value for xueqiu_stock_shareschg.circskamt
     *
     * @mbggenerated
     */
    public void setCircskamt(Double circskamt) {
        this.circskamt = circskamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_shareschg.ncircamt
     *
     * @return the value of xueqiu_stock_shareschg.ncircamt
     *
     * @mbggenerated
     */
    public Double getNcircamt() {
        return ncircamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_shareschg.ncircamt
     *
     * @param ncircamt the value for xueqiu_stock_shareschg.ncircamt
     *
     * @mbggenerated
     */
    public void setNcircamt(Double ncircamt) {
        this.ncircamt = ncircamt;
    }
}