package com.diffwind.dao.model;

import java.util.Date;

public class XueqiuStockFinance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.reportdate
     *
     * @mbggenerated
     */
    private Date reportdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.basiceps
     *
     * @mbggenerated
     */
    private Double basiceps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.epsdiluted
     *
     * @mbggenerated
     */
    private Double epsdiluted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.epsweighted
     *
     * @mbggenerated
     */
    private Double epsweighted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.naps
     *
     * @mbggenerated
     */
    private Double naps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.opercashpershare
     *
     * @mbggenerated
     */
    private Double opercashpershare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.peropecashpershare
     *
     * @mbggenerated
     */
    private Double peropecashpershare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.netassgrowrate
     *
     * @mbggenerated
     */
    private Double netassgrowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.dilutedroe
     *
     * @mbggenerated
     */
    private Double dilutedroe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.weightedroe
     *
     * @mbggenerated
     */
    private Double weightedroe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.mainbusincgrowrate
     *
     * @mbggenerated
     */
    private Double mainbusincgrowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.netincgrowrate
     *
     * @mbggenerated
     */
    private Double netincgrowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.totassgrowrate
     *
     * @mbggenerated
     */
    private Double totassgrowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.salegrossprofitrto
     *
     * @mbggenerated
     */
    private Double salegrossprofitrto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.mainbusiincome
     *
     * @mbggenerated
     */
    private Double mainbusiincome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.mainbusiprofit
     *
     * @mbggenerated
     */
    private Double mainbusiprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.totprofit
     *
     * @mbggenerated
     */
    private Double totprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.netprofit
     *
     * @mbggenerated
     */
    private Double netprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.totalassets
     *
     * @mbggenerated
     */
    private Double totalassets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.totalliab
     *
     * @mbggenerated
     */
    private Double totalliab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.totsharequi
     *
     * @mbggenerated
     */
    private Double totsharequi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.operrevenue
     *
     * @mbggenerated
     */
    private Double operrevenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.invnetcashflow
     *
     * @mbggenerated
     */
    private Double invnetcashflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.finnetcflow
     *
     * @mbggenerated
     */
    private Double finnetcflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.chgexchgchgs
     *
     * @mbggenerated
     */
    private Double chgexchgchgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.cashnetr
     *
     * @mbggenerated
     */
    private Double cashnetr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueqiu_stock_finance.cashequfinbal
     *
     * @mbggenerated
     */
    private Double cashequfinbal;
    
    
    //
    private String hycode;
    private String hyname;
    
    private Date piluDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.symbol
     *
     * @return the value of xueqiu_stock_finance.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.symbol
     *
     * @param symbol the value for xueqiu_stock_finance.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.name
     *
     * @return the value of xueqiu_stock_finance.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.name
     *
     * @param name the value for xueqiu_stock_finance.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.reportdate
     *
     * @return the value of xueqiu_stock_finance.reportdate
     *
     * @mbggenerated
     */
    public Date getReportdate() {
        return reportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.reportdate
     *
     * @param reportdate the value for xueqiu_stock_finance.reportdate
     *
     * @mbggenerated
     */
    public void setReportdate(Date reportdate) {
        this.reportdate = reportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.basiceps
     *
     * @return the value of xueqiu_stock_finance.basiceps
     *
     * @mbggenerated
     */
    public Double getBasiceps() {
        return basiceps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.basiceps
     *
     * @param basiceps the value for xueqiu_stock_finance.basiceps
     *
     * @mbggenerated
     */
    public void setBasiceps(Double basiceps) {
        this.basiceps = basiceps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.epsdiluted
     *
     * @return the value of xueqiu_stock_finance.epsdiluted
     *
     * @mbggenerated
     */
    public Double getEpsdiluted() {
        return epsdiluted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.epsdiluted
     *
     * @param epsdiluted the value for xueqiu_stock_finance.epsdiluted
     *
     * @mbggenerated
     */
    public void setEpsdiluted(Double epsdiluted) {
        this.epsdiluted = epsdiluted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.epsweighted
     *
     * @return the value of xueqiu_stock_finance.epsweighted
     *
     * @mbggenerated
     */
    public Double getEpsweighted() {
        return epsweighted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.epsweighted
     *
     * @param epsweighted the value for xueqiu_stock_finance.epsweighted
     *
     * @mbggenerated
     */
    public void setEpsweighted(Double epsweighted) {
        this.epsweighted = epsweighted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.naps
     *
     * @return the value of xueqiu_stock_finance.naps
     *
     * @mbggenerated
     */
    public Double getNaps() {
        return naps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.naps
     *
     * @param naps the value for xueqiu_stock_finance.naps
     *
     * @mbggenerated
     */
    public void setNaps(Double naps) {
        this.naps = naps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.opercashpershare
     *
     * @return the value of xueqiu_stock_finance.opercashpershare
     *
     * @mbggenerated
     */
    public Double getOpercashpershare() {
        return opercashpershare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.opercashpershare
     *
     * @param opercashpershare the value for xueqiu_stock_finance.opercashpershare
     *
     * @mbggenerated
     */
    public void setOpercashpershare(Double opercashpershare) {
        this.opercashpershare = opercashpershare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.peropecashpershare
     *
     * @return the value of xueqiu_stock_finance.peropecashpershare
     *
     * @mbggenerated
     */
    public Double getPeropecashpershare() {
        return peropecashpershare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.peropecashpershare
     *
     * @param peropecashpershare the value for xueqiu_stock_finance.peropecashpershare
     *
     * @mbggenerated
     */
    public void setPeropecashpershare(Double peropecashpershare) {
        this.peropecashpershare = peropecashpershare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.netassgrowrate
     *
     * @return the value of xueqiu_stock_finance.netassgrowrate
     *
     * @mbggenerated
     */
    public Double getNetassgrowrate() {
        return netassgrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.netassgrowrate
     *
     * @param netassgrowrate the value for xueqiu_stock_finance.netassgrowrate
     *
     * @mbggenerated
     */
    public void setNetassgrowrate(Double netassgrowrate) {
        this.netassgrowrate = netassgrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.dilutedroe
     *
     * @return the value of xueqiu_stock_finance.dilutedroe
     *
     * @mbggenerated
     */
    public Double getDilutedroe() {
        return dilutedroe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.dilutedroe
     *
     * @param dilutedroe the value for xueqiu_stock_finance.dilutedroe
     *
     * @mbggenerated
     */
    public void setDilutedroe(Double dilutedroe) {
        this.dilutedroe = dilutedroe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.weightedroe
     *
     * @return the value of xueqiu_stock_finance.weightedroe
     *
     * @mbggenerated
     */
    public Double getWeightedroe() {
        return weightedroe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.weightedroe
     *
     * @param weightedroe the value for xueqiu_stock_finance.weightedroe
     *
     * @mbggenerated
     */
    public void setWeightedroe(Double weightedroe) {
        this.weightedroe = weightedroe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.mainbusincgrowrate
     *
     * @return the value of xueqiu_stock_finance.mainbusincgrowrate
     *
     * @mbggenerated
     */
    public Double getMainbusincgrowrate() {
        return mainbusincgrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.mainbusincgrowrate
     *
     * @param mainbusincgrowrate the value for xueqiu_stock_finance.mainbusincgrowrate
     *
     * @mbggenerated
     */
    public void setMainbusincgrowrate(Double mainbusincgrowrate) {
        this.mainbusincgrowrate = mainbusincgrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.netincgrowrate
     *
     * @return the value of xueqiu_stock_finance.netincgrowrate
     *
     * @mbggenerated
     */
    public Double getNetincgrowrate() {
        return netincgrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.netincgrowrate
     *
     * @param netincgrowrate the value for xueqiu_stock_finance.netincgrowrate
     *
     * @mbggenerated
     */
    public void setNetincgrowrate(Double netincgrowrate) {
        this.netincgrowrate = netincgrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.totassgrowrate
     *
     * @return the value of xueqiu_stock_finance.totassgrowrate
     *
     * @mbggenerated
     */
    public Double getTotassgrowrate() {
        return totassgrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.totassgrowrate
     *
     * @param totassgrowrate the value for xueqiu_stock_finance.totassgrowrate
     *
     * @mbggenerated
     */
    public void setTotassgrowrate(Double totassgrowrate) {
        this.totassgrowrate = totassgrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.salegrossprofitrto
     *
     * @return the value of xueqiu_stock_finance.salegrossprofitrto
     *
     * @mbggenerated
     */
    public Double getSalegrossprofitrto() {
        return salegrossprofitrto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.salegrossprofitrto
     *
     * @param salegrossprofitrto the value for xueqiu_stock_finance.salegrossprofitrto
     *
     * @mbggenerated
     */
    public void setSalegrossprofitrto(Double salegrossprofitrto) {
        this.salegrossprofitrto = salegrossprofitrto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.mainbusiincome
     *
     * @return the value of xueqiu_stock_finance.mainbusiincome
     *
     * @mbggenerated
     */
    public Double getMainbusiincome() {
        return mainbusiincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.mainbusiincome
     *
     * @param mainbusiincome the value for xueqiu_stock_finance.mainbusiincome
     *
     * @mbggenerated
     */
    public void setMainbusiincome(Double mainbusiincome) {
        this.mainbusiincome = mainbusiincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.mainbusiprofit
     *
     * @return the value of xueqiu_stock_finance.mainbusiprofit
     *
     * @mbggenerated
     */
    public Double getMainbusiprofit() {
        return mainbusiprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.mainbusiprofit
     *
     * @param mainbusiprofit the value for xueqiu_stock_finance.mainbusiprofit
     *
     * @mbggenerated
     */
    public void setMainbusiprofit(Double mainbusiprofit) {
        this.mainbusiprofit = mainbusiprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.totprofit
     *
     * @return the value of xueqiu_stock_finance.totprofit
     *
     * @mbggenerated
     */
    public Double getTotprofit() {
        return totprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.totprofit
     *
     * @param totprofit the value for xueqiu_stock_finance.totprofit
     *
     * @mbggenerated
     */
    public void setTotprofit(Double totprofit) {
        this.totprofit = totprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.netprofit
     *
     * @return the value of xueqiu_stock_finance.netprofit
     *
     * @mbggenerated
     */
    public Double getNetprofit() {
        return netprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.netprofit
     *
     * @param netprofit the value for xueqiu_stock_finance.netprofit
     *
     * @mbggenerated
     */
    public void setNetprofit(Double netprofit) {
        this.netprofit = netprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.totalassets
     *
     * @return the value of xueqiu_stock_finance.totalassets
     *
     * @mbggenerated
     */
    public Double getTotalassets() {
        return totalassets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.totalassets
     *
     * @param totalassets the value for xueqiu_stock_finance.totalassets
     *
     * @mbggenerated
     */
    public void setTotalassets(Double totalassets) {
        this.totalassets = totalassets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.totalliab
     *
     * @return the value of xueqiu_stock_finance.totalliab
     *
     * @mbggenerated
     */
    public Double getTotalliab() {
        return totalliab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.totalliab
     *
     * @param totalliab the value for xueqiu_stock_finance.totalliab
     *
     * @mbggenerated
     */
    public void setTotalliab(Double totalliab) {
        this.totalliab = totalliab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.totsharequi
     *
     * @return the value of xueqiu_stock_finance.totsharequi
     *
     * @mbggenerated
     */
    public Double getTotsharequi() {
        return totsharequi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.totsharequi
     *
     * @param totsharequi the value for xueqiu_stock_finance.totsharequi
     *
     * @mbggenerated
     */
    public void setTotsharequi(Double totsharequi) {
        this.totsharequi = totsharequi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.operrevenue
     *
     * @return the value of xueqiu_stock_finance.operrevenue
     *
     * @mbggenerated
     */
    public Double getOperrevenue() {
        return operrevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.operrevenue
     *
     * @param operrevenue the value for xueqiu_stock_finance.operrevenue
     *
     * @mbggenerated
     */
    public void setOperrevenue(Double operrevenue) {
        this.operrevenue = operrevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.invnetcashflow
     *
     * @return the value of xueqiu_stock_finance.invnetcashflow
     *
     * @mbggenerated
     */
    public Double getInvnetcashflow() {
        return invnetcashflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.invnetcashflow
     *
     * @param invnetcashflow the value for xueqiu_stock_finance.invnetcashflow
     *
     * @mbggenerated
     */
    public void setInvnetcashflow(Double invnetcashflow) {
        this.invnetcashflow = invnetcashflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.finnetcflow
     *
     * @return the value of xueqiu_stock_finance.finnetcflow
     *
     * @mbggenerated
     */
    public Double getFinnetcflow() {
        return finnetcflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.finnetcflow
     *
     * @param finnetcflow the value for xueqiu_stock_finance.finnetcflow
     *
     * @mbggenerated
     */
    public void setFinnetcflow(Double finnetcflow) {
        this.finnetcflow = finnetcflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.chgexchgchgs
     *
     * @return the value of xueqiu_stock_finance.chgexchgchgs
     *
     * @mbggenerated
     */
    public Double getChgexchgchgs() {
        return chgexchgchgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.chgexchgchgs
     *
     * @param chgexchgchgs the value for xueqiu_stock_finance.chgexchgchgs
     *
     * @mbggenerated
     */
    public void setChgexchgchgs(Double chgexchgchgs) {
        this.chgexchgchgs = chgexchgchgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.cashnetr
     *
     * @return the value of xueqiu_stock_finance.cashnetr
     *
     * @mbggenerated
     */
    public Double getCashnetr() {
        return cashnetr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.cashnetr
     *
     * @param cashnetr the value for xueqiu_stock_finance.cashnetr
     *
     * @mbggenerated
     */
    public void setCashnetr(Double cashnetr) {
        this.cashnetr = cashnetr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueqiu_stock_finance.cashequfinbal
     *
     * @return the value of xueqiu_stock_finance.cashequfinbal
     *
     * @mbggenerated
     */
    public Double getCashequfinbal() {
        return cashequfinbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueqiu_stock_finance.cashequfinbal
     *
     * @param cashequfinbal the value for xueqiu_stock_finance.cashequfinbal
     *
     * @mbggenerated
     */
    public void setCashequfinbal(Double cashequfinbal) {
        this.cashequfinbal = cashequfinbal;
    }
    
    
    private Double eps4q;

	public Double getEps4q() {
		return eps4q;
	}

	public void setEps4q(Double eps4q) {
		this.eps4q = eps4q;
	}

	public String getHycode() {
		return hycode;
	}

	public void setHycode(String hycode) {
		this.hycode = hycode;
	}

	public String getHyname() {
		return hyname;
	}

	public void setHyname(String hyname) {
		this.hyname = hyname;
	}

	public Date getPiluDate() {
		return piluDate;
	}

	public void setPiluDate(Date piluDate) {
		this.piluDate = piluDate;
	}
	
    
}