package com.diffwind.dao.mapper;

import java.util.List;

import com.diffwind.dao.model.EastmoneyStockRzrqJson;

public interface EastmoneyStockRzrqJsonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eastmoney_stock_rzrq_json
     *
     * @mbggenerated
     */
    int insert(EastmoneyStockRzrqJson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eastmoney_stock_rzrq_json
     *
     * @mbggenerated
     */
    List<EastmoneyStockRzrqJson> selectAll();
}