package com.diffwind.dao.mapper;

import java.util.List;

import com.diffwind.dao.model.EastmoneyStockBbsj;

public interface EastmoneyStockBbsjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eastmoney_stock_bbsj
     *
     * @mbggenerated
     */
    int insert(EastmoneyStockBbsj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eastmoney_stock_bbsj
     *
     * @mbggenerated
     */
    List<EastmoneyStockBbsj> selectAll();
}