package com.diffwind.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.diffwind.dao.model.SinaZjhhangyeStock;

public interface SinaZjhhangyeStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_zjhhangye_stock
     *
     * @mbggenerated
     */
    int insert(SinaZjhhangyeStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_zjhhangye_stock
     *
     * @mbggenerated
     */
    List<SinaZjhhangyeStock> selectAll();
    
    
    List<SinaZjhhangyeStock> selectBySymbol(@Param("symbol") String symbol);
    
    List<String> selectHyBySymbol(@Param("symbol") String symbol);
    
    List<SinaZjhhangyeStock> selectAllStockHangye();
    
}