package com.diffwind.dao.mapper;

import java.util.List;

import com.diffwind.dao.model.SinaZjhhangye;

public interface SinaZjhhangyeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_zjhhangye
     *
     * @mbggenerated
     */
    int insert(SinaZjhhangye record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_zjhhangye
     *
     * @mbggenerated
     */
    List<SinaZjhhangye> selectAll();
}