package com.diffwind.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.diffwind.dao.model.TdxStockDay;

public interface TdxStockDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_stock_day
     *
     * @mbggenerated
     */
    int insert(TdxStockDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdx_stock_day
     *
     * @mbggenerated
     */
    List<TdxStockDay> selectAll();
    
    
    void batchInsert(@Param("records") List<TdxStockDay> records);
    
    List<TdxStockDay> selectBySymbol(@Param("symbol") String symbol, @Param("isDesc") boolean isDesc);
    
   void batchInsertPartition(@Param("partition") String partition, @Param("records") List<TdxStockDay> records);
    
    void truncatePartition(@Param("partition") String partition);
    

}