package com.diffwind.dao.mapper;

import java.util.List;

import com.diffwind.dao.model.XueqiuStock;

public interface XueqiuStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueqiu_stock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String symbol);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueqiu_stock
     *
     * @mbggenerated
     */
    int insert(XueqiuStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueqiu_stock
     *
     * @mbggenerated
     */
    XueqiuStock selectByPrimaryKey(String symbol);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueqiu_stock
     *
     * @mbggenerated
     */
    List<XueqiuStock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueqiu_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XueqiuStock record);
}