package com.diffwind.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.diffwind.dao.model.XueqiuStockFinance;

public interface XueqiuStockFinanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueqiu_stock_finance
     *
     * @mbggenerated
     */
    int insert(XueqiuStockFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueqiu_stock_finance
     *
     * @mbggenerated
     */
    List<XueqiuStockFinance> selectAll();
    
    
    List<XueqiuStockFinance> selectBySymbol(@Param("symbol") String symbol);
    
    List<XueqiuStockFinance> selectAllStkLastReportdate();
    
    List<XueqiuStockFinance> selectByYingli5Y();
    
    List<XueqiuStockFinance> selectForClusterAnalysis();
    
    List<XueqiuStockFinance> selectBySymbol5Y(@Param("symbol") String symbol);

}