package com.diffwind.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.diffwind.dao.model.XueqiuStockShareschg;

public interface XueqiuStockShareschgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueqiu_stock_shareschg
     *
     * @mbggenerated
     */
    int insert(XueqiuStockShareschg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueqiu_stock_shareschg
     *
     * @mbggenerated
     */
    List<XueqiuStockShareschg> selectAll();
    
    
    List<XueqiuStockShareschg> selectBySymbol(@Param("symbol") String symbol);
    
    List<XueqiuStockShareschg> selectAllStkLastShareschg();

}